<?xml version="1.0" encoding="utf-8"?>
<TestRecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Results>
    <UnitTestResult>
      <TestDate>2011-02-21T17:09:55</TestDate>
      <Status>Success</Status>
      <TotalFailures>0</TotalFailures>
      <TotalSuccess>3</TotalSuccess>
      <TotalIgnored>0</TotalIgnored>
      <Time />
    </UnitTestResult>
    <UnitTestResult>
      <TestDate>2011-02-21T17:10:37</TestDate>
      <Status>Success Failure</Status>
      <TotalFailures>1</TotalFailures>
      <TotalSuccess>2</TotalSuccess>
      <TotalIgnored>0</TotalIgnored>
      <Time />
      <Message>Child test failed</Message>
    </UnitTestResult>
  </Results>
  <Tests>
    <TestRecord Name="nodecs">
      <Results />
      <Tests>
        <TestRecord Name="test">
          <Results />
          <Tests>
            <TestRecord Name="PreconditionsTests">
              <Results>
                <UnitTestResult>
                  <TestDate>2011-02-21T09:10:33</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>1</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Child test failed</Message>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T09:10:51</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>1</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Child test failed</Message>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T09:11:29</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>1</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Child test failed</Message>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T09:13:52</TestDate>
                  <Status>Success</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>1</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                </UnitTestResult>
              </Results>
              <Tests>
                <TestRecord Name="TestIt">
                  <Results>
                    <UnitTestResult>
                      <TestDate>2011-02-21T09:10:33</TestDate>
                      <Status>Failure</Status>
                      <TotalFailures>1</TotalFailures>
                      <TotalSuccess>0</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>System.Exception : Failed</Message>
                      <StackTrace>   at nodecs.Preconditions.throwException(Type exceptionType, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 18
   at nodecs.Preconditions.IsTrue[T](Boolean value, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 25
   at nodecs.Preconditions.IsTrue(Boolean value, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 10
   at nodecs.test.PreconditionsTests.TestIt() in c:\dev\Node.cs\nodecs.test\Exceptions\PreconditionsTests.cs:line 11</StackTrace>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T09:10:51</TestDate>
                      <Status>Failure</Status>
                      <TotalFailures>1</TotalFailures>
                      <TotalSuccess>0</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>System.Exception : Failed</Message>
                      <StackTrace>   at nodecs.Preconditions.throwException(Type exceptionType, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 18
   at nodecs.Preconditions.IsTrue[T](Boolean value, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 25
   at nodecs.Preconditions.IsTrue(Boolean value, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 10
   at nodecs.test.PreconditionsTests.TestIt() in c:\dev\Node.cs\nodecs.test\Exceptions\PreconditionsTests.cs:line 11</StackTrace>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T09:11:29</TestDate>
                      <Status>Failure</Status>
                      <TotalFailures>1</TotalFailures>
                      <TotalSuccess>0</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>System.Exception : Failed</Message>
                      <StackTrace>   at nodecs.Preconditions.throwException(Type exceptionType, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 18
   at nodecs.Preconditions.IsTrue[T](Boolean value, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 25
   at nodecs.Preconditions.IsTrue(Boolean value, String message, String[] paramList) in c:\dev\Node.cs\nodecs\Exceptions\Preconditions.cs:line 10
   at nodecs.test.PreconditionsTests.TestIt() in c:\dev\Node.cs\nodecs.test\Exceptions\PreconditionsTests.cs:line 14</StackTrace>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T09:13:52</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.02ms</Message>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                  </Results>
                  <Tests />
                </TestRecord>
              </Tests>
            </TestRecord>
            <TestRecord Name="HeapTests">
              <Results />
              <Tests>
                <TestRecord Name="TestInsertion">
                  <Results>
                    <UnitTestResult>
                      <TestDate>2011-02-21T15:34:47</TestDate>
                      <Status>Failure</Status>
                      <TotalFailures>1</TotalFailures>
                      <TotalSuccess>0</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>  oopsie
  Expected: True
  But was:  False
</Message>
                      <StackTrace>   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.IsTrue(Boolean condition, String message)
   at nodecs.test.HeapTests.TestInsertion() in c:\dev\Node.cs\nodecs.test\Collections\HeapTests.cs:line 40</StackTrace>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T16:11:20</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 43.87ms</Message>
                      <ConsoleOutput>sorted list
1669228142
1619533884
876816043
Heap
0
0
0
</ConsoleOutput>
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T16:13:12</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.04ms</Message>
                      <ConsoleOutput>sorted list
1238737361
915427052
881581691
Heap
1238737361
915427052
881581691
</ConsoleOutput>
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T16:13:20</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 145.20ms</Message>
                      <ConsoleOutput>sorted list
2110387594
1777021815
1049831904
Heap
2110387594
1777021815
1049831904
</ConsoleOutput>
                      <ConsoleError />
                    </UnitTestResult>
                  </Results>
                  <Tests />
                </TestRecord>
              </Tests>
            </TestRecord>
          </Tests>
        </TestRecord>
      </Tests>
    </TestRecord>
    <TestRecord Name="NodeCS">
      <Results>
        <UnitTestResult>
          <TestDate>2011-02-21T17:09:55</TestDate>
          <Status>Success</Status>
          <TotalFailures>0</TotalFailures>
          <TotalSuccess>3</TotalSuccess>
          <TotalIgnored>0</TotalIgnored>
          <Time />
        </UnitTestResult>
        <UnitTestResult>
          <TestDate>2011-02-21T17:10:37</TestDate>
          <Status>Success Failure</Status>
          <TotalFailures>1</TotalFailures>
          <TotalSuccess>2</TotalSuccess>
          <TotalIgnored>0</TotalIgnored>
          <Time />
          <Message>Child test failed</Message>
        </UnitTestResult>
      </Results>
      <Tests>
        <TestRecord Name="test">
          <Results>
            <UnitTestResult>
              <TestDate>2011-02-21T17:09:55</TestDate>
              <Status>Success</Status>
              <TotalFailures>0</TotalFailures>
              <TotalSuccess>3</TotalSuccess>
              <TotalIgnored>0</TotalIgnored>
              <Time />
            </UnitTestResult>
            <UnitTestResult>
              <TestDate>2011-02-21T17:10:37</TestDate>
              <Status>Success Failure</Status>
              <TotalFailures>1</TotalFailures>
              <TotalSuccess>2</TotalSuccess>
              <TotalIgnored>0</TotalIgnored>
              <Time />
              <Message>Child test failed</Message>
            </UnitTestResult>
          </Results>
          <Tests>
            <TestRecord Name="HeapTests">
              <Results>
                <UnitTestResult>
                  <TestDate>2011-02-21T17:09:55</TestDate>
                  <Status>Success</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>2</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T17:10:37</TestDate>
                  <Status>Success Failure</Status>
                  <TotalFailures>1</TotalFailures>
                  <TotalSuccess>1</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Child test failed</Message>
                </UnitTestResult>
              </Results>
              <Tests>
                <TestRecord Name="TestAscendingSort">
                  <Results>
                    <UnitTestResult>
                      <TestDate>2011-02-21T17:09:55</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.08ms</Message>
                      <ConsoleOutput>Time for 10000 56
</ConsoleOutput>
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T17:10:37</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.08ms</Message>
                      <ConsoleOutput>Time for 10000 56
</ConsoleOutput>
                      <ConsoleError />
                    </UnitTestResult>
                  </Results>
                  <Tests />
                </TestRecord>
                <TestRecord Name="TestDecendingSort">
                  <Results>
                    <UnitTestResult>
                      <TestDate>2011-02-21T17:09:55</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.04ms</Message>
                      <ConsoleOutput>Time for 10000 37
</ConsoleOutput>
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T17:10:37</TestDate>
                      <Status>Failure</Status>
                      <TotalFailures>1</TotalFailures>
                      <TotalSuccess>0</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>  Expected: 276903
  But was:  2147145257
</Message>
                      <StackTrace>   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Int32 expected, Int32 actual)
   at NodeCS.test.HeapTests.TestDecendingSort() in c:\dev\Node.cs\nodecs.test\Collections\HeapTests.cs:line 40</StackTrace>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                  </Results>
                  <Tests />
                </TestRecord>
              </Tests>
            </TestRecord>
            <TestRecord Name="PreconditionsTests">
              <Results>
                <UnitTestResult>
                  <TestDate>2011-02-21T17:09:55</TestDate>
                  <Status>Success</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>1</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T17:10:37</TestDate>
                  <Status>Success</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>1</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                </UnitTestResult>
              </Results>
              <Tests>
                <TestRecord Name="TestIt">
                  <Results>
                    <UnitTestResult>
                      <TestDate>2011-02-21T17:09:55</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.00ms</Message>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                    <UnitTestResult>
                      <TestDate>2011-02-21T17:10:37</TestDate>
                      <Status>Success</Status>
                      <TotalFailures>0</TotalFailures>
                      <TotalSuccess>1</TotalSuccess>
                      <TotalIgnored>0</TotalIgnored>
                      <Time />
                      <Message>Test successful

Execution time: 0.00ms</Message>
                      <ConsoleOutput />
                      <ConsoleError />
                    </UnitTestResult>
                  </Results>
                  <Tests />
                </TestRecord>
              </Tests>
            </TestRecord>
          </Tests>
        </TestRecord>
      </Tests>
    </TestRecord>
    <TestRecord Name="EventLoop">
      <Tests>
        <TestRecord Name="LoopTests">
          <Tests>
            <TestRecord Name="TestIt">
              <Results>
                <UnitTestResult>
                  <TestDate>2011-02-21T21:04:45</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Object reference not set to an instance of an object</Message>
                  <StackTrace>
Server stack trace: 
  at MonoDevelop.NUnit.External.EventListenerWrapper.GetLocalTestResult (NUnit.Core.TestResult t) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper remoting-invoke-with-check) MonoDevelop.NUnit.External.EventListenerWrapper:GetLocalTestResult (NUnit.Core.TestResult)
  at MonoDevelop.NUnit.External.ExternalTestRunner.Run (IRemoteEventListener listener, ITestFilter filter, System.String path, System.String suiteName, System.Collections.Generic.List`1 supportAssemblies) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&amp;)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, IMethodCallMessage reqMsg) [0x000ad] in C:\cygwin\tmp\monobuild\build\BUILD\mono-2.10\mcs\class\corlib\System.Runtime.Remoting\RemotingServices.cs:138 

Exception rethrown at [0]: 
   at MonoDevelop.NUnit.NUnitAssemblyTestSuite.RunUnitTest(UnitTest test, String suiteName, String testName, TestContext testContext)
   at MonoDevelop.NUnit.NUnitTestCase.OnRun(TestContext testContext)
   at MonoDevelop.NUnit.UnitTest.Run(TestContext testContext)</StackTrace>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T21:05:14</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Object reference not set to an instance of an object</Message>
                  <StackTrace>
Server stack trace: 
  at MonoDevelop.NUnit.External.EventListenerWrapper.GetLocalTestResult (NUnit.Core.TestResult t) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper remoting-invoke-with-check) MonoDevelop.NUnit.External.EventListenerWrapper:GetLocalTestResult (NUnit.Core.TestResult)
  at MonoDevelop.NUnit.External.ExternalTestRunner.Run (IRemoteEventListener listener, ITestFilter filter, System.String path, System.String suiteName, System.Collections.Generic.List`1 supportAssemblies) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&amp;)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, IMethodCallMessage reqMsg) [0x000ad] in C:\cygwin\tmp\monobuild\build\BUILD\mono-2.10\mcs\class\corlib\System.Runtime.Remoting\RemotingServices.cs:138 

Exception rethrown at [0]: 
   at MonoDevelop.NUnit.NUnitAssemblyTestSuite.RunUnitTest(UnitTest test, String suiteName, String testName, TestContext testContext)
   at MonoDevelop.NUnit.NUnitTestCase.OnRun(TestContext testContext)
   at MonoDevelop.NUnit.UnitTest.Run(TestContext testContext)</StackTrace>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T21:05:31</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Object reference not set to an instance of an object</Message>
                  <StackTrace>
Server stack trace: 
  at MonoDevelop.NUnit.External.EventListenerWrapper.GetLocalTestResult (NUnit.Core.TestResult t) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper remoting-invoke-with-check) MonoDevelop.NUnit.External.EventListenerWrapper:GetLocalTestResult (NUnit.Core.TestResult)
  at MonoDevelop.NUnit.External.ExternalTestRunner.Run (IRemoteEventListener listener, ITestFilter filter, System.String path, System.String suiteName, System.Collections.Generic.List`1 supportAssemblies) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&amp;)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, IMethodCallMessage reqMsg) [0x000ad] in C:\cygwin\tmp\monobuild\build\BUILD\mono-2.10\mcs\class\corlib\System.Runtime.Remoting\RemotingServices.cs:138 

Exception rethrown at [0]: 
   at MonoDevelop.NUnit.NUnitAssemblyTestSuite.RunUnitTest(UnitTest test, String suiteName, String testName, TestContext testContext)
   at MonoDevelop.NUnit.NUnitTestCase.OnRun(TestContext testContext)
   at MonoDevelop.NUnit.UnitTest.Run(TestContext testContext)</StackTrace>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T21:05:46</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>0</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>Object reference not set to an instance of an object</Message>
                  <StackTrace>
Server stack trace: 
  at MonoDevelop.NUnit.External.EventListenerWrapper.GetLocalTestResult (NUnit.Core.TestResult t) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper remoting-invoke-with-check) MonoDevelop.NUnit.External.EventListenerWrapper:GetLocalTestResult (NUnit.Core.TestResult)
  at MonoDevelop.NUnit.External.ExternalTestRunner.Run (IRemoteEventListener listener, ITestFilter filter, System.String path, System.String suiteName, System.Collections.Generic.List`1 supportAssemblies) [0x00000] in &lt;filename unknown&gt;:0 
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&amp;)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, IMethodCallMessage reqMsg) [0x000ad] in C:\cygwin\tmp\monobuild\build\BUILD\mono-2.10\mcs\class\corlib\System.Runtime.Remoting\RemotingServices.cs:138 

Exception rethrown at [0]: 
   at MonoDevelop.NUnit.NUnitAssemblyTestSuite.RunUnitTest(UnitTest test, String suiteName, String testName, TestContext testContext)
   at MonoDevelop.NUnit.NUnitTestCase.OnRun(TestContext testContext)
   at MonoDevelop.NUnit.UnitTest.Run(TestContext testContext)</StackTrace>
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T21:06:02</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>1</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>System.MissingMethodException : Cannot find the requested method.</Message>
                  <StackTrace>  at (wrapper managed-to-native) EventLoop.LoopTests:Select_internal (System.Net.Sockets.Socket[]&amp;,int,int&amp;)
  at EventLoop.LoopTests.TestIt () [0x0003d] in C:\dev\Node.cs\nodecs.test\EventLoop\LoopTests.cs:32 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in C:\cygwin\tmp\monobuild\build\BUILD\mono-2.10\mcs\class\corlib\System.Reflection\MonoMethod.cs:226 </StackTrace>
                  <ConsoleOutput />
                  <ConsoleError />
                </UnitTestResult>
                <UnitTestResult>
                  <TestDate>2011-02-21T21:10:05</TestDate>
                  <Status>Failure</Status>
                  <TotalFailures>1</TotalFailures>
                  <TotalSuccess>0</TotalSuccess>
                  <TotalIgnored>0</TotalIgnored>
                  <Time />
                  <Message>System.MissingMethodException : Cannot find the requested method.</Message>
                  <StackTrace>  at (wrapper managed-to-native) EventLoop.LoopTests:Select_internal (System.Net.Sockets.Socket[]&amp;,int,int&amp;)
  at EventLoop.LoopTests.TestIt () [0x00047] in C:\dev\Node.cs\nodecs.test\EventLoop\LoopTests.cs:35 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in C:\cygwin\tmp\monobuild\build\BUILD\mono-2.10\mcs\class\corlib\System.Reflection\MonoMethod.cs:226 </StackTrace>
                  <ConsoleOutput>dfsdf
</ConsoleOutput>
                  <ConsoleError />
                </UnitTestResult>
              </Results>
            </TestRecord>
          </Tests>
        </TestRecord>
      </Tests>
    </TestRecord>
  </Tests>
</TestRecord>